### ISSUE TITLE
World backs up every time a world is entered, timer resetting?

### ISSUE THREAD

**Issue by Gbergz** [ChaoticTrials/SimpleBackups#2]
### Minecraft version

1.18.1

### Simple Backups version

1.0.1

### Forge version

39.1.2

### The latest.log file

No log for the issue.

### Issue description

The world starts a backup every time a world is entered, is the timer resetting?

### Steps to reproduce

1. Install mod.
2. Enter World.
3. Backups start.
4. Quit world.
5. Rejoin world.
6. Backkup starts again regardless of what the timer is set to in the config.
7. Done.

### Other information

Or is this intentional? Doesn't feel like it. Reporting this anyways.

**Comment by MelanX** [comment]
This is intentional. This is mainly for servers. When a player leaves, a last backup will be done in the normal schedule. While nobody is online, there are no more backups. When the next player joins, a new backup will be created.
This does not happen when you’re re-joining too quickly. If the timespan is shorter than the normal schedule, no backup will be created. 
Thanks for reporting anyway!

**Comment by Gbergz** [comment]
Ah, gotcha. Thanks for the reply! :)
