### ISSUE TITLE
Not working on 1.18.1

### ISSUE THREAD

**Issue by Sebulba46** [ChaoticTrials/SimpleBackups#3]
### Minecraft version

1.18.1

### Simple Backups version

1.18.2-1.1.4

### Forge version

39.1.0

### The latest.log file

https://gist.github.com/Sebulba46/2a3ada7463b2cb67759df308bdaaef1f

### Issue description

I guess it's not working on 1.18.1, but you mentioned: 
Revert "Allow 1.18.2 version on 1.18.1" - MelanX

### Steps to reproduce

Start server

**Comment by MelanX** [comment]
Yes, I reverted the previous change called "Allow 1.18.2 version on 1.18.1". This reverts the ability to use it on 1.18.1.
Mojang did a few changes which makes the 1.18.2 versions of the mod incompatible with 1.18.1. To be clear, it's basically one single change which affects this mod.
Since mods are updating to 1.18.2, you could use the 1.18.1 versions for now and update in the near future to have all the new features and fixed things.
